apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: solo-leveling-api
spec:
  template:
    spec:
      containers:
        - image: REGION-docker.pkg.dev/PROJECT_ID/solo-leveling/api:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: USE_IN_MEMORY_DB
              value: "false"
